# Generated by Django 4.2.17 on 2024-12-05 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('buildings', models.TextField(blank=True, null=True)),
                ('people', models.TextField(blank=True, null=True)),
                ('resources', models.TextField(blank=True, null=True)),
                ('owner_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
