# Generated by Django 4.2.17 on 2024-12-05 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tile_images/'),
        ),
    ]
