# Generated by Django 4.2.17 on 2024-12-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_remove_tile_owner_id_remove_tile_people_tile_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='display_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
