# Generated by Django 4.2.17 on 2024-12-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_profile_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='color',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AddField(
            model_name='tile',
            name='terrain',
            field=models.CharField(choices=[('fields', 'Fields'), ('mountains', 'Mountains'), ('forest', 'Forest'), ('plains', 'Plains'), ('water', 'Water')], default='plains', max_length=10),
        ),
    ]
