# Generated by Django 4.2.17 on 2024-12-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_profile_color_tile_terrain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tile',
            name='terrain',
            field=models.CharField(choices=[('fields', 'Fields'), ('mountains', 'Mountains'), ('forest', 'Forest'), ('plains', 'Plains'), ('water', 'Water'), ('city', 'City')], default='plains', max_length=10),
        ),
    ]
