# Generated by Django 4.2.17 on 2024-12-16 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_tile_goods_queuedaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversalGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
