# Generated by Django 4.2.17 on 2024-12-22 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_gamedate_tile_moving_goods_statusaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedate',
            name='current_date',
            field=models.DateField(default=datetime.date(1100, 1, 1)),
        ),
    ]
