# Generated by Django 4.2.17 on 2024-12-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_alter_gamedate_current_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tile',
            name='moving_goods',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
